version: "3"
services:
    nginx:
        build: ./nginx
        volumes:
            - ./src:/var/www/html
        links:
            - php
        ports:
            - "80:80"
        container_name: nginx
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "3306:3306"
        container_name: mysql
    redis:
        image: redis
        ports:
            - "6379:6379"
        container_name: redis
    php:
        build: ./php
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: sh -c "php-fpm"
        depends_on:
            - mysql
        container_name: php
